FROM mariadb

# Instalar cron
RUN apt-get update && apt-get install -y cron

# Copiar el script de copia de seguridad en el contenedor
RUN apt-get install nano

RUN echo "* * * * * /bin/bash -c 'docker exec -i docker-db-1 /bin/bash -c \"cd sql && mariadb-dump -u root -psecret MercaDAW > copiaSeguridad.sql\"'" | crontab -



