FROM mariadb

# Instalación de cron
RUN apt-get update && apt-get -y install cron

# Copiar el script de copia de seguridad al contenedor
COPY scriptCopiaSeguridad.sh /sql/scriptCopiaSeguridad.sh

# Configuración de la tarea cron
RUN echo "5 * * * * root /bin/bash /sql/scriptCopiaSeguridad.sh" > /etc/cron.d/copia_seguridad

# Iniciar cron en segundo plano
CMD ["cron", "-f"]