@startuml Modelo-Vista-Controlador
title Modelo-Vista-Controlador
left to right direction
package view{
    component InicioViewController <<java>> as inicioController
    component GestionProductoViewController <<java>> as gestionProdController
    component GestionEmpleadoViewController <<java>> as gestionEmpController

    component inicioView <<FXML file>> as inicioView
    component gestionProductoView <<FXML file>> as gestionProdView
    component gestionEmpleadoView <<FXML file>> as gestionEmpView
}

package controller{
    component MercaDawController as mdc
}

package model{
    component MercaDaw
    component Dao 
    component LectorImp

    () "MercadoDAO" as dao
    () "Gestionable" as gestion
    () "Lector" as lectorif

    MercaDaw -() gestion
    Dao -() dao
    LectorImp -() lectorif

}

mdc ..> gestion : use
MercaDaw ..> dao : use

    inicioController ..> inicioView: use
    gestionProdController ..> gestionProdView: use
    gestionEmpController ..> gestionEmpView: use

    gestionProdController ..> mdc: use
    gestionEmpController ..> mdc: use
    inicioController ..> mdc: use

dao ..> lectorif

@enduml