@startuml Diagrama clases Mercado
set separator none
allow_mixing
left to right direction
package es.etg.programacion.mercadaw{
    package model{
        package mercado{
            class Supermercado{
                    -provincia: String
                    -municipio: String
            }       
             
            class MercadoFactory{
                +{static}crearProducto(c: Categoria): IProducto
                +{static}crearTrabajador(trab: Trabajador): IEmpleado
            }
            interface Gestionable{
                +darAltaEmpleado(nombre: String, apellido:String, categoria: Trabajador): IEmpleado
                +darAltaProducto(producto: Producto): IProducto
                +obtenerEmpleados(): List<Empleado>
                +obtenerProducto(): List<Producto>

            }
        }
        package producto{
            abstract Producto{
                +IVA: double 
                -nombre: String
                -marca: String
                -precioEnEuros: double
                -alturaEnMetros: double
                -anchuraEnMetros: double
                -pesoEnKg: double
                -numElementos: int
                -descripcion: String
                -categoria: String
                +toString(): String
                +imprimirEtiqueta(): String
                +build(): ProductoBuilder
            }

            interface IProducto{
                +calcularPrecio(): Double[]
                +imprimirInfoPrecio(p: Double[])
            }
                
            class Alimentacion{
                +IVA:double = 0.04
            }
            class Drogueria{
                +IVA:double = 0.10
            }

            class Cosmetica{
                +IVA:double = 0.21
            }
        
        }
        package trabajador{
            class Empleado{
                +SALARIO: double = 1000
                -{static} id: int
                -nombre: String
                -apellido: String
                -categoria: String
            }
            class Reponedor{
                +SALARIO: double = 1200
            }
            class Cajero{
                +SALARIO: double = 1300
            }
            class Encargado{
                +SALARIO: double = 1500
            }

            interface IEmpleado{
                +calcularNomina():Nomina
                +toString(): String
            }
            }
        
        package util{
            interface Documento{
                +getContenido():Map<String,String>
                +getTitulo():String
                +getPie():String
            }
        package print{
            class Impresora{
                +imprimir(fichero:String)
            }
            }
        package writer{
            class WriterMarkDown{
                +{static}escribir(contratable:IEmpleado)
                +{static}escribir(doc:Documento)
                +{static}escribirEtiqueta(Producto)
                +{static}escribir(docs:List<Documento>)
                }
            }
        package reader{
            interface Lector{
                +leer(fichero:String)
            }
            class LectorXML{
                +leer(fichero:String)
            }
            class LectorSQL{
                +leer(fichero:String)
            }
                Lector <|.. LectorXML
                Lector <|.. LectorSQL
            }
        Documento <|.. Producto
        Documento <|.. Empleado
        }
        package dao{
            interface MercadoDAO{

                +listarEmpleados(): list<Empleado>
                +listarProductos(): list<Producto>
                +anadir(producto: Producto): int
                +anadir(empleado: Empleado): int 
                +eliminar(empleado: Empleado): int
                +eliminar(producto: Producto): int


            }
            class MercadoMariadbDAOImp{
                -connection: Connection
            }
            class MercadoMockDAOImp{

            }
            enum Modo{
                MOCK, MARIADB
            }
        
        MercadoDAO <|.. MercadoMariadbDAOImp
        MercadoDAO <|.. MercadoMockDAOImp
        }
         
    }
} 
component "org.mariadb.jdbc"<<jdbc driver>> 

"org.mariadb.jdbc" <.. MercadoMariadbDAOImp




Supermercado o-- Producto
Supermercado o-- Empleado
IProducto <|.. Producto
Producto <|-- Alimentacion
Producto <|-- Drogueria
Producto <|-- Cosmetica
Empleado <|-- Reponedor
Empleado <|-- Cajero
Empleado <|-- Encargado
Gestionable <|.. Supermercado
IEmpleado <|.. Empleado


@enduml

@startuml Diagrama clases lector
set separator none
package es.etg.daw{

}

@enduml
