--VISTA POR CODIGO POSTAL:
CREATE OR REPLACE VIEW COMPRAS_POR_CODIGO_POSTAL AS
SELECT C.CODIGO_POSTAL, CP.ID_COMPRA,  CP.CLIENTES_ID, CP.PRODUCTOS_ID, CP.CANTIDAD, CP.FECHA_COMPRA
FROM CLIENTES C, COMPRA CP
WHERE C.ID = CP.CLIENTES_ID
ORDER BY 1 ASC;
--VISTA STOCK PRODUCTOS: 
CREATE OR REPLACE VIEW STOCK_PRODUCTOS AS
SELECT S.PRODUCTOS_ID, P.NOMBRE, S.CANTIDAD 
FROM STOCK S, PRODUCTOS P 
WHERE S.PRODUCTOS_ID = P.ID;